# mkdocs file for generating microsite
site_name: Generative AI Architecture Patterns
nav:
   - Home: index.md
   - About This Book: about.md
   - Concepts:
     - Introduction: concepts/index.md
     - Large-language Models: concepts/large-language-models.md
     - Agents: concepts/agents.md
     - Chatbots: concepts/chatbots.md
     - Embeddings: concepts/embeddings.md
     - Concept Index: concepts/concept-index.md
     - Knowledge Graph: concepts/knowledge-graph.ms
   - Patterns:
     - Introduction: patterns/index.md
     - Prompt Enrichment: patterns/prompt-enrichment.md
     - Finetuning: patterns/finetuning.md
     - Agent: patterns/agent.md
     - Code Interpreter: patterns/code-interpreter.md
     - Knowledge Representation: patterns/knowledge-representation.md
     - Similarity: patterns/similarity.md
   - Talks: talks.md
   - Contributing: contributing.md
   - Glossary: glossary.md
   - References: references.md
   - Contact: contact.md
repo_name: 'Go to GitHub'
repo_url: 'https://github.com/dmccreary/genai-arch-patterns'
edit_uri: 'blob/master/docs'
copyright: 'Copyright &copy; 2023 Dan McCreary'
theme:
  name: material
  feature:
    tabs: false
markdown_extensions:
  - admonition
  - pymdownx.details  
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences