# mkdocs file for generating microsite
site_name: Generative AI Architecture Patterns
nav:
   - Home: index.md
   - About This Book: about.md
   - Events: events.md

   - Concepts:
     - Introduction: concepts/index.md
     - Terminology and Standards: concepts/architecture-standards.md
     - Large-language Models: concepts/large-language-models.md
     - Agents: concepts/agents.md
     - Chatbots: concepts/chatbots.md
     - Embeddings: concepts/embeddings.md
     - Concept Index: concepts/concept-index.md
     - Knowledge Graph: concepts/knowledge-graph.md
     - Cosine Similarity: concepts/cosine-similarity.md
     - Vector Database: concepts/vector-database.md
   
   - Patterns:
     - Introduction: patterns/index.md
     - Prompt Enrichment: patterns/prompt-enrichment.md
     - Finetuning: patterns/finetuning.md
     - Agent: patterns/agents.md
     - Code Interpreter: patterns/code-interpreter.md
     - Knowledge Representation: patterns/knowledge-representation.md
     - RAG: patterns/rag.md
     - Similarity: patterns/similarity.md
   
   - Micro Simulations:
      - Introductions: sims/index.md

   
   - Prompts:
     - Introduction: prompts/index.md
     - GenAI Arch Trends: prompts/genai-arch-trends.md
     - Update the README.md: prompts/update-readme.md
     - Word Cloud: prompts/word-cloud/index.md
     - Knowledge Graph:
       - Introduction: prompts/knowledge-graph/index.md
       - prompts/knowledge-graph/concept-enumeration.md
       - prompts/knowledge-graph/concept-dependency.md
       - prompts/knowledge-graph/concept-taxonomy.md 
   - Talks: talks.md
   - Contributing: contributing.md
   - Glossary: glossary.md
   - References: references.md
   - Contact: contact.md
   - How We Built This Site: how-we-built-this-site.md
repo_name: 'Go to GitHub'
repo_url: 'https://github.com/dmccreary/genai-arch-patterns'
edit_uri: 'blob/master/docs'
copyright: 'Copyright &copy; 2023 Dan McCreary'
theme:
  name: material
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
markdown_extensions:
  - admonition
  - pymdownx.details  
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
# Google Analytics MEASUREMENT ID: G-QD0XE8V1HL
# https://analytics.google.com/analytics/web/?authuser=0#/p406011100/reports/intelligenthome
extra:
    analytics:
       provider: google
       property: G-QD0XE8V1HL
